version: '3.8'

services:
  backend:
    build:
      context: ./server 
    container_name: chess_backend

  frontend:
    build:
      context: ./app 
    container_name: chess_frontend

  proxy:
    image: nginx:1.27-alpine-slim
    container_name: chess_proxy
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - backend
      - frontend