version: '3.8'

services:
  # Serviço do Backend (seu servidor WebSocket)
  backend:
    build:
      context: ./server # Pasta onde está o Dockerfile do backend
    container_name: chess_backend
    # Não precisa de 'ports' porque o acesso será via proxy

  # Serviço do Frontend (apenas para servir os arquivos para o Nginx)
  frontend:
    build:
      context: ./app # Pasta onde está o Dockerfile do frontend
    container_name: chess_frontend
    # Também não precisa de 'ports'

  # Serviço do Proxy (Nginx) - O ponto de entrada público
  proxy:
    image: nginx:1.27-alpine-slim
    container_name: chess_proxy
    ports:
      - "80:80" # Mapeia a porta 80 do seu EC2 para a porta 80 do contêiner Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Monta nosso arquivo de configuração
    depends_on:
      - backend
      - frontend