version: '3.8'

services:
  frontend:
    container_name: chess_frontend
    build:
      context: ./app   # pasta do seu front
      dockerfile: Dockerfile
    ports:
      - "80:80"   # expõe o front na porta 80
    depends_on:
      - backend

  backend:
    container_name: chess_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8080"   # expõe só internamente para o frontend
